spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=False&sevetTimezone=UTC
    username: root
    password: 2003
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8088
api:
  prefix: api/v1